/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.poo2;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import static proyecto.poo2.AdminF.contenedorEnca;
import static proyecto.poo2.AdminF.contenedorProf;

/**
 *
 * @author rober
 */
public class EncargadoF extends javax.swing.JFrame {
    public static LinkedList contenedorEquipos = new LinkedList();
    public int buscar;
    public boolean Operativo;
    /**
     * Creates new form EncargadoF
     */
    public EncargadoF() {
        initComponents();
        this.setLocationRelativeTo(null);
        int contador = 0;
        
        File archivo = new File("C:/Users/Public/hardware.txt");
        if(archivo.exists()){
        try{
        ObjectInputStream abrirEquipo = new ObjectInputStream(new FileInputStream("C:/Users/Public/hardware.txt"));
        contenedorEquipos = (LinkedList) abrirEquipo.readObject();
        abrirEquipo.close();


        }
        catch(Exception e){
             JOptionPane.showConfirmDialog(null, "Error Fatal", 
            "Aviso",JOptionPane.DEFAULT_OPTION,JOptionPane.WARNING_MESSAGE);
        }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        operatividadC = new javax.swing.ButtonGroup();
        operartividadCr = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombreEquipo = new javax.swing.JTextField();
        Agregar = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        marcaEquipo = new javax.swing.JTextField();
        Fabricacion = new javax.swing.JTextField();
        numSerieEquipo = new javax.swing.JTextField();
        numLab = new javax.swing.JTextField();
        MostrarTabla = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        numeroSede = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        laboratorio = new javax.swing.JTextField();
        sede = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        numSerie1 = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        marca = new javax.swing.JTextField();
        año = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        estaOperativo = new javax.swing.JRadioButton();
        noEstaOperativo = new javax.swing.JRadioButton();
        RBOperativo = new javax.swing.JRadioButton();
        noOperativo = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Nombre Equipo");

        jLabel3.setText("Ingrese n° de Serie:");

        nombreEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreEquipoActionPerformed(evt);
            }
        });

        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        jLabel1.setText("Modificar Equipo");

        jLabel4.setText("Agregar nuevo equipo");

        jLabel5.setText("Marca del Equipo");

        jLabel6.setText("Año de Fabricación");

        jLabel7.setText("N° de Serie");

        jLabel8.setText("N° de Laboratorio");

        MostrarTabla.setText("Mostrar Tabla");
        MostrarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarTablaActionPerformed(evt);
            }
        });

        jLabel9.setText("Sede");

        jLabel10.setText("Operatividad");

        jLabel11.setText("Año");

        jLabel12.setText("Laboratorio");

        jLabel13.setText("Sede");

        numSerie1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numSerie1KeyTyped(evt);
            }
        });

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        jLabel14.setText("Operatividad");

        jLabel15.setText("Nombre");

        jLabel16.setText("Marca");

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        operatividadC.add(estaOperativo);
        estaOperativo.setText("si");
        estaOperativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estaOperativoActionPerformed(evt);
            }
        });

        operatividadC.add(noEstaOperativo);
        noEstaOperativo.setText("no");
        noEstaOperativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noEstaOperativoActionPerformed(evt);
            }
        });

        operartividadCr.add(RBOperativo);
        RBOperativo.setText("si");
        RBOperativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBOperativoActionPerformed(evt);
            }
        });

        operartividadCr.add(noOperativo);
        noOperativo.setText("no");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(numSerie1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(año, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(73, 73, 73)
                                        .addComponent(jLabel15)
                                        .addGap(74, 74, 74)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(noEstaOperativo)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addGap(64, 64, 64)
                                                .addComponent(jLabel11)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(296, 296, 296)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(55, 55, 55))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel13)
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel14))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(laboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addComponent(sede, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RBOperativo)
                                            .addComponent(noOperativo))))
                                .addGap(14, 14, 14))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Agregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MostrarTabla)
                        .addGap(131, 131, 131))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel10))
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numSerieEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(numeroSede, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nombreEquipo, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(marcaEquipo, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Fabricacion, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(numLab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                                    .addComponent(estaOperativo))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(numSerieEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(marcaEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Fabricacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(numLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(numeroSede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(estaOperativo)
                    .addComponent(noEstaOperativo))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Agregar)
                    .addComponent(MostrarTabla))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RBOperativo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numSerie1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(noOperativo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Modificar)
                    .addComponent(jButton1))
                .addGap(90, 90, 90))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        String numS = numSerieEquipo.getText();
        String nomE = nombreEquipo.getText();  
        String marE = marcaEquipo.getText(); 
        String af = Fabricacion.getText();
        String numL = numLab.getText();
        String Sede = numeroSede.getText();
        boolean operatividad = Operativo;
        
      
        
        
        if(numS.isEmpty() || nomE.isEmpty() || marE.isEmpty() || af.isEmpty() || numL.isEmpty() || Sede.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese todos los datos");
            
        } else {
            JOptionPane.showMessageDialog(null, "Nuevo equipo agregado");
            Equipos claseequipos = new Equipos(numS,nomE,marE,af,numL,Sede,operatividad);
            contenedorEquipos.add(claseequipos);
            guardarEquipos();
            numSerieEquipo.setText(null);
            nombreEquipo.setText(null);
            marcaEquipo.setText(null);
            Fabricacion.setText(null);
            numLab.setText(null);
            numeroSede.setText(null);
            estaOperativo.setSelected(false);
            noEstaOperativo.setSelected(false);
        }
        
    }//GEN-LAST:event_AgregarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        String numS = numSerie1.getText();
        String nomE = nombre.getText();  
        String marE = marca.getText(); 
        String af = año.getText();
        String numL = laboratorio.getText();
        String Sede = sede.getText();
        boolean opE = Operativo;
        
        if(numS.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingreso el numero de serie del equipo");
            
        } else {
            Equipos u;
            String SeriePrueba = String.valueOf(numSerie1.getText());
            for(int i = 0; i < EncargadoF.contenedorEquipos.size(); i++){
                u = (Equipos)contenedorEquipos.get(i);
                String igualador = String.valueOf(u.getN_serie());
                if(igualador.equals(SeriePrueba)){
                    System.out.println("modificando");
                    u.setEstadoOperatividad(opE);
                    u.setN_serie(numS);
                    u.setSede(Sede);
                    u.setMarca(marE);
                    u.setLaboratorio(numL);
                    u.setAñoFabricacion(af);
                    u.setNombre(nomE);
                    
                    contenedorEquipos.set(i, u);
                    break;
                }
                else{
                    continue;
                     
                }
            }
            guardarEquipos();
            numSerie1.setText(null);
            nombre.setText(null);
            marca.setText(null);
            año.setText(null);
            laboratorio.setText(null);
            sede.setText(null);
            RBOperativo.setSelected(false);
            noOperativo.setSelected(false);
           
        }
    }//GEN-LAST:event_ModificarActionPerformed

    private void nombreEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreEquipoActionPerformed

    private void MostrarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarTablaActionPerformed
        // TODO add your handling code here:
        DatosInventario mostrar = new DatosInventario();
        mostrar.setVisible(true);
    }//GEN-LAST:event_MostrarTablaActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void numSerie1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numSerie1KeyTyped
        // TODO add your handling code here:
        int press=evt.getKeyChar();
        if(press==10){
            String idencontrado=numSerie1.getText().trim();
            Equipos a;
            for (int i=0; i<contenedorEquipos.size(); i++){
                a = (Equipos)contenedorEquipos.get(i);
                if(idencontrado.equalsIgnoreCase(a.getN_serie())){
                    nombre.setText(a.getNombre());
                    marca.setText(a.getMarca());
                    año.setText(a.getAñoFabricacion());
                    laboratorio.setText(a.getLaboratorio());
                    sede.setText(a.getSede());
                    Operativo = a.getEstadoOperatividad();
                    if(Operativo == true){
                        RBOperativo.setSelected(true);
                        noOperativo.setSelected(false);
                    }
                    else{
                        RBOperativo.setSelected(false);
                        noOperativo.setSelected(true);
                    }
                }
            }
        }
    }//GEN-LAST:event_numSerie1KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Sistema().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void estaOperativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estaOperativoActionPerformed
        // TODO add your handling code here:
        Operativo = true;
    }//GEN-LAST:event_estaOperativoActionPerformed

    private void noEstaOperativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noEstaOperativoActionPerformed
        // TODO add your handling code here:
        Operativo = false;
    }//GEN-LAST:event_noEstaOperativoActionPerformed

    private void RBOperativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBOperativoActionPerformed
        // TODO add your handling code here:
        Operativo = true;
    }//GEN-LAST:event_RBOperativoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EncargadoF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EncargadoF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EncargadoF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EncargadoF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EncargadoF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JTextField Fabricacion;
    private javax.swing.JButton Modificar;
    private javax.swing.JButton MostrarTabla;
    private javax.swing.JRadioButton RBOperativo;
    private javax.swing.JTextField año;
    private javax.swing.JRadioButton estaOperativo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField laboratorio;
    private javax.swing.JTextField marca;
    private javax.swing.JTextField marcaEquipo;
    private javax.swing.JRadioButton noEstaOperativo;
    private javax.swing.JRadioButton noOperativo;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField nombreEquipo;
    private javax.swing.JTextField numLab;
    private javax.swing.JTextField numSerie1;
    private javax.swing.JTextField numSerieEquipo;
    private javax.swing.JTextField numeroSede;
    private javax.swing.ButtonGroup operartividadCr;
    private javax.swing.ButtonGroup operatividadC;
    private javax.swing.JTextField sede;
    // End of variables declaration//GEN-END:variables

public void guardarEquipos(){
    try{
        ObjectOutputStream GuardarEquipo = new ObjectOutputStream(new FileOutputStream("C:/Users/Public/hardware.txt"));
        GuardarEquipo.writeObject(contenedorEquipos);
        GuardarEquipo.close();
       
        }
        catch(Exception e){
             JOptionPane.showConfirmDialog(null, "Error al Guardar Archivos", 
            "Aviso",JOptionPane.DEFAULT_OPTION,JOptionPane.WARNING_MESSAGE);
        }
}
}
