/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.poo2;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import static proyecto.poo2.EncargadoF.contenedorEquipos;

/**
 *
 * @author rober
 */
public class ProfesorF extends javax.swing.JFrame {
    boolean operativos;
    /**
     * Creates new form ProfesorF
     */
    public ProfesorF() {
        initComponents();
        this.setLocationRelativeTo(null);
         File archivo = new File("C:/Users/Public/hardware.txt");
        if(archivo.exists()){
        try{
        ObjectInputStream abrirEquipo = new ObjectInputStream(new FileInputStream("C:/Users/Public/hardware.txt"));
        contenedorEquipos = (LinkedList) abrirEquipo.readObject();
        abrirEquipo.close();


        }
        catch(Exception e){
             JOptionPane.showConfirmDialog(null, "Archivo no existe, genere base de datos", 
            "Aviso",JOptionPane.DEFAULT_OPTION,JOptionPane.WARNING_MESSAGE);
        }
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        serial = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Operativo = new javax.swing.JRadioButton();
        noOperativo = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        nombre = new javax.swing.JTextField();
        marca = new javax.swing.JTextField();
        año = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        laboratorio = new javax.swing.JTextField();
        sede = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        op = new javax.swing.JRadioButton();
        nop = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Modificar Operatividad");

        serial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialActionPerformed(evt);
            }
        });
        serial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                serialKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                serialKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                serialKeyTyped(evt);
            }
        });

        jLabel4.setText("N° de Serie del equipo");

        buttonGroup1.add(Operativo);
        Operativo.setText("Operativo");
        Operativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OperativoActionPerformed(evt);
            }
        });

        buttonGroup1.add(noOperativo);
        noOperativo.setText("No Operativo");
        noOperativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noOperativoActionPerformed(evt);
            }
        });

        jButton1.setText("Modificar");
        jButton1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jButton1AncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Mostrar Tabla");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        nombre.setEditable(false);
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        marca.setEditable(false);

        año.setEditable(false);

        jLabel1.setText("Nombre");

        jLabel5.setText("Marca");

        jLabel6.setText("Año");

        laboratorio.setEditable(false);

        sede.setEditable(false);

        jLabel7.setText("Laboratorio");

        jLabel8.setText("Sede");

        jLabel9.setText("Operatividad");

        jButton3.setText("Cerrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        buttonGroup6.add(op);
        op.setText("Operativo");
        op.setEnabled(false);

        buttonGroup6.add(nop);
        nop.setText("No Operativo");
        nop.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Operativo)
                                    .addComponent(noOperativo)))
                            .addGap(92, 92, 92)
                            .addComponent(jButton2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(serial, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(año, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(197, 197, 197)
                                    .addComponent(jLabel1)
                                    .addGap(74, 74, 74)
                                    .addComponent(jLabel5)
                                    .addGap(64, 64, 64)
                                    .addComponent(jLabel6)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(26, 26, 26)
                                    .addComponent(jLabel8)
                                    .addGap(36, 36, 36)
                                    .addComponent(jLabel9))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(laboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(24, 24, 24)
                                    .addComponent(sede, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nop)
                                        .addComponent(op)))))))
                .addGap(79, 79, 79))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(op))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Operativo)
                    .addComponent(nop))
                .addGap(5, 5, 5)
                .addComponent(noOperativo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String numS = serial.getText();
        String nomE = nombre.getText();
        String marE = marca.getText();
        String añoE = año.getText();
        String labE = laboratorio.getText();
        String sedeE = sede.getText();
        boolean OpE =operativos;
        

        
        if(numS.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese numero de serie del equipo a modificar");
            
        } else {
            Equipos u;
            String SeriePrueba = String.valueOf(serial.getText());
            for(int i = 0; i < EncargadoF.contenedorEquipos.size(); i++){
                u = (Equipos)contenedorEquipos.get(i);
                String igualador = u.getN_serie();
                if(igualador.equals(SeriePrueba) ){
                    u.setEstadoOperatividad(operativos);
                    break;
                }
                else{
                    continue;
                }
            }
             guardarEquipos();
             JOptionPane.showMessageDialog(null, "Operatividad modificada");
             serial.setText(null);
             nombre.setText(null);
             marca.setText(null);
             año.setText(null);
             laboratorio.setText(null);
             sede.setText(null);
             Operativo.setSelected(false);
             noOperativo.setSelected(false);
             op.setSelected(false);
             nop.setSelected(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DatosInventario mostrar = new DatosInventario();
        mostrar.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void noOperativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noOperativoActionPerformed
        // TODO add your handling code here:
        operativos =false;
    }//GEN-LAST:event_noOperativoActionPerformed

    private void OperativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OperativoActionPerformed
        // TODO add your handling code here:
        operativos = true;
    }//GEN-LAST:event_OperativoActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Sistema().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton1AncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1AncestorMoved

    private void serialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serialKeyTyped
        // TODO add your handling code here:
    
    }//GEN-LAST:event_serialKeyTyped

    private void serialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serialKeyReleased
        // TODO add your handling code here:
Equipos u;
        String buscador = String.valueOf(serial.getText());
            for(int i = 0; i < EncargadoF.contenedorEquipos.size(); i++) {
                
                u = (Equipos)contenedorEquipos.get(i);
                String Comparador = String.valueOf(u.getN_serie());
                if(buscador.equals(Comparador)){
                    nombre.setText(u.getNombre());
                    marca.setText(u.getMarca());
                    año.setText(u.getAñoFabricacion());
                    laboratorio.setText(u.getLaboratorio());
                    sede.setText(u.getSede());
                    if(u.getEstadoOperatividad() == true){
                        op.setSelected(true);
                        nop.setSelected(false);
                    }
                    else{
                        op.setSelected(false);
                        nop.setSelected(true);
                    }
                    break;
                }
                else{
                    
                    continue;
                }
            }
    }//GEN-LAST:event_serialKeyReleased

    private void serialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serialKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_serialKeyPressed

    private void serialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialActionPerformed
        // TODO add your handling code here:
          
    }//GEN-LAST:event_serialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfesorF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfesorF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfesorF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfesorF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfesorF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Operativo;
    private javax.swing.JTextField año;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField laboratorio;
    private javax.swing.JTextField marca;
    private javax.swing.JRadioButton noOperativo;
    private javax.swing.JTextField nombre;
    private javax.swing.JRadioButton nop;
    private javax.swing.JRadioButton op;
    private javax.swing.JTextField sede;
    private javax.swing.JTextField serial;
    // End of variables declaration//GEN-END:variables
public void guardarEquipos(){
    try{
        ObjectOutputStream GuardarEquipo = new ObjectOutputStream(new FileOutputStream("C:/Users/Public/hardware.txt"));
        GuardarEquipo.writeObject(contenedorEquipos);
        GuardarEquipo.close();
       
        }
        catch(Exception e){
             JOptionPane.showConfirmDialog(null, "Error al Guardar Archivos", 
            "Aviso",JOptionPane.DEFAULT_OPTION,JOptionPane.WARNING_MESSAGE);
        }
}
}
